# Configuration for request-info - https://github.com/behaviorbot/request-info

# Comment to reply with
requestInfoReplyComment: >
  Hey there! It looks like you didn't provide much information here. Please
  consider adding more details about the issue / pr or it will be automatically
  closed. Thanks for helping us maintain the project!

# default titles to check against for lack of descriptiveness
requestInfoDefaultTitles:
  - update readme.md
  - updates
  - fix
  - fixes

requestInfoLabelToAdd: more information needed


# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening your first pull request in the Outline project ðŸŽ‰ðŸ™Œ! One of the core
  team members will take a look and get back to you soon with approval or requested
  changes.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  A big thanks on merging your first pull request into Outline!
  ![awesome](https://media.giphy.com/media/fDzM81OYrNjJC/giphy.gif)
