services:

  outline:
      container_name: outline
      build:
        context: .
        dockerfile: Dockerfile
      env_file: ./docker.env
      expose:
        - "3000"
      volumes:
        - storage-data:/var/lib/outline/data
      depends_on:
        - postgres
        - redis

  redis:
    container_name: redis
    image: redis
    env_file: ./docker.env
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres
    env_file: ./docker.env
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outlinedb", "-U", "outlinedbadmin"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
      - ./nginx-conf:/var/lib/https-portal/nginx-conf
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      HTTPS_PORTAL_STAGE: 'production'
      DOMAINS: 'scruffy.is.ed.ac.uk -> http://outline:3000'
      STAGE: 'local'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'
      WEBSOCKET_SUPPORT: 'true'
      KEEPALIVE_TIMEOUT: '70s'
      PROXY_READ_TIMEOUT: '60s'
      PROXY_SEND_TIMEOUT: '60s'

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    expose:
      - "9000"
    environment:
      - TZ=Europe/London

volumes:
  https-portal-data:
  storage-data:
  database-data:
  portainer-data:
